# Medical Learning Platform Configuration

# Environment
environment: development  # development, staging, production

# API Keys (use environment variables in production)
api_keys:
  anthropic: ${ANTHROPIC_API_KEY}
  openai: ${OPENAI_API_KEY}
  google: ${GOOGLE_API_KEY}

# Database Configuration
database:
  postgres:
    host: localhost
    port: 5432
    database: studyin
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    pool_size: 20
    max_overflow: 10

  redis:
    host: localhost
    port: 6379
    db: 0
    password: ${REDIS_PASSWORD}
    decode_responses: true

# Vector Database (Qdrant)
vector_db:
  host: localhost
  port: 6333
  collection_name: medical_knowledge
  vector_size: 384
  distance_metric: cosine
  prefer_grpc: true

# LLM Configuration
llm:
  default_model: claude-3.5-sonnet
  fallback_models:
    - gpt-4o-mini
    - gemini-1.5-flash

  timeout: 30  # seconds
  max_retries: 3
  retry_delay: 1  # seconds

  # Model-specific settings
  models:
    claude-3.5-sonnet:
      max_tokens: 4000
      temperature: 0.7
      rate_limit: 50  # requests per minute

    gpt-4o-mini:
      max_tokens: 4000
      temperature: 0.7
      rate_limit: 500

    gemini-1.5-flash:
      max_tokens: 4000
      temperature: 0.7
      rate_limit: 100

# RAG Configuration
rag:
  chunking:
    strategy: hybrid  # semantic, hierarchical, sliding, hybrid
    chunk_size: 512  # tokens
    overlap: 128  # tokens
    preserve_structure: true

  retrieval:
    top_k: 10
    use_reranking: true
    rerank_top_k: 5
    min_score: 0.6
    use_hybrid_search: true

  embedding:
    model: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 32
    normalize_embeddings: true

# Caching Configuration
cache:
  strategy: hybrid  # exact, semantic, parametric, hybrid
  ttl: 3600  # seconds (1 hour)
  similarity_threshold: 0.92
  max_cache_size: 10000
  enable_semantic_cache: true

# Cost Optimization
cost_optimization:
  enabled: true
  daily_budget: 10.0  # USD
  hourly_budget: 1.0  # USD
  enable_request_coalescing: true
  coalescing_window_ms: 100

  # Auto-scaling settings
  auto_adjust_difficulty: true
  min_cache_hit_rate: 0.3
  target_cache_hit_rate: 0.7

# Learning Engine Configuration
learning:
  target_accuracy: 0.75  # Target 75% accuracy
  difficulty_adjustment_window: 5  # questions
  max_consecutive_wrong: 3

  # Session settings
  default_session_length: 20  # questions
  warmup_questions: 3
  review_interval_days: [1, 3, 7, 14, 30]  # Spaced repetition

  # Adaptive settings
  enable_socratic_teaching: true
  enable_mnemonic_generation: true
  enable_performance_tracking: true

# API Server Configuration
server:
  host: 0.0.0.0
  port: 8000
  workers: 4
  reload: true  # Only in development

  # CORS
  cors:
    enabled: true
    origins:
      - http://localhost:3000
      - http://localhost:8080
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Monitoring and Logging
monitoring:
  enable_prometheus: true
  prometheus_port: 9090

  logging:
    level: INFO  # DEBUG, INFO, WARNING, ERROR
    format: json
    log_file: logs/studyin.log
    max_file_size: 100MB
    backup_count: 5

  sentry:
    enabled: false
    dsn: ${SENTRY_DSN}
    environment: ${ENVIRONMENT}
    traces_sample_rate: 0.1

# Security
security:
  enable_api_key_auth: true
  jwt_secret: ${JWT_SECRET}
  jwt_algorithm: HS256
  access_token_expire_minutes: 60

  # Rate limiting per user
  user_rate_limit:
    requests_per_hour: 100
    questions_per_day: 200

# Feature Flags
features:
  enable_image_questions: false
  enable_audio_explanations: false
  enable_collaborative_learning: false
  enable_ai_coach: true
  enable_performance_analytics: true
  enable_adaptive_difficulty: true

# Medical Content Configuration
medical_content:
  supported_formats:
    - pdf
    - txt
    - docx
    - md

  validation:
    require_medical_accuracy_check: true
    enable_citation_tracking: true

  topics:
    - Anatomy
    - Biochemistry
    - Physiology
    - Pathology
    - Pharmacology
    - Microbiology
    - Immunology
    - Behavioral Science
    - Biostatistics

# USMLE Step 1 Specific Settings
usmle:
  question_types:
    - single_best_answer
    - clinical_vignette
    - image_based
    - lab_values

  difficulty_distribution:
    basic: 0.2
    intermediate: 0.3
    advanced: 0.3
    expert: 0.2

  time_per_question: 90  # seconds
  passing_score: 0.60

# Development Settings
development:
  debug: true
  auto_reload: true
  mock_llm_calls: false
  seed_database: true

# Production Settings
production:
  debug: false
  auto_reload: false
  enable_ssl: true
  ssl_cert: /path/to/cert.pem
  ssl_key: /path/to/key.pem