version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=studyin
      - DB_USER=studyin_user
      - DB_PASSWORD=${DB_PASSWORD:-changeme}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clamav:
        condition: service_started
    volumes:
      - ..:/app
      - uploads:/var/www/studyin/uploads

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: studyin
      POSTGRES_USER: studyin_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U studyin_user']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    ports:
      - '6379:6379'

  clamav:
    image: clamav/clamav:latest
    container_name: studyin_clamav
    ports:
      - '3310:3310'
    volumes:
      - clamav-data:/var/lib/clamav
    healthcheck:
      test: ['CMD', 'clamdscan', '--ping', '1']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  uploads:
  clamav-data:
