version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-studyin_staging}
      POSTGRES_USER: ${DB_USER:-studyin_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5433:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    ports:
      - "6380:6379"
    volumes:
      - redis_staging_data:/data

  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
      - ../.env.staging
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
      - clamav
    volumes:
      - ../:/app:ro
      - uploads_staging:/app/uploads
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_staging_data:
  redis_staging_data:
  uploads_staging:
