name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Unit tests (Vitest)
        run: npm test

      - name: Generate analytics snapshot
        run: npm run analyze

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright)
        env:
          CI: true
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

