name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI: true
      FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Validate items (evidence gate enforced)
        env:
          REQUIRE_EVIDENCE_CROP: '1'
        run: npm run validate:items

      - name: Run unit tests
        run: npm test

      - name: Run analyze
        run: npm run analyze

      - name: Build Next.js app
        run: npm run build

      - name: Rubric score (non-blocking)
        run: npm run score:rubric || true

      - name: Upload analytics artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analytics-outputs
          path: |
            public/analytics/latest.json
            public/analytics/rubric-score.json

      # Lighthouse and axe disabled/removed for this phase.
